# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(89, 122, 170, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(89, 122, 170, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.sidebar.setObjectName("sidebar")
        self.btnProfileSidebar = QtWidgets.QPushButton(self.sidebar)
        self.btnProfileSidebar.setGeometry(QtCore.QRect(0, 0, 100, 80))
        self.btnProfileSidebar.setStyleSheet("background-color: rgb(40, 57, 83); \n"
"color: white;\n"
"font: 16pt \"Lora\";")
        self.btnProfileSidebar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProfileSidebar.setIcon(icon)
        self.btnProfileSidebar.setIconSize(QtCore.QSize(70, 70))
        self.btnProfileSidebar.setObjectName("btnProfileSidebar")
        self.btnExitSidebar = QtWidgets.QPushButton(self.sidebar)
        self.btnExitSidebar.setGeometry(QtCore.QRect(0, 400, 100, 80))
        self.btnExitSidebar.setStyleSheet("background-color: rgb(74, 0, 0);\n"
"color: white;\n"
"font: 16pt \"Lora\";")
        self.btnExitSidebar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExitSidebar.setIcon(icon1)
        self.btnExitSidebar.setIconSize(QtCore.QSize(60, 60))
        self.btnExitSidebar.setObjectName("btnExitSidebar")
        self.btnStatsSidebar = QtWidgets.QPushButton(self.sidebar)
        self.btnStatsSidebar.setGeometry(QtCore.QRect(0, 79, 100, 81))
        self.btnStatsSidebar.setStyleSheet("background-color: rgb(40, 57, 83); \n"
"color: white;\n"
"font: 16pt \"Lora\";")
        self.btnStatsSidebar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/analytics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStatsSidebar.setIcon(icon2)
        self.btnStatsSidebar.setIconSize(QtCore.QSize(60, 60))
        self.btnStatsSidebar.setObjectName("btnStatsSidebar")
        self.btnRatingSidebar = QtWidgets.QPushButton(self.sidebar)
        self.btnRatingSidebar.setGeometry(QtCore.QRect(0, 160, 100, 80))
        self.btnRatingSidebar.setStyleSheet("background-color: rgb(40, 57, 83); \n"
"color: white;\n"
"font: 16pt \"Lora\";")
        self.btnRatingSidebar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/rating.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRatingSidebar.setIcon(icon3)
        self.btnRatingSidebar.setIconSize(QtCore.QSize(60, 60))
        self.btnRatingSidebar.setObjectName("btnRatingSidebar")
        self.btnResourcesSidebar = QtWidgets.QPushButton(self.sidebar)
        self.btnResourcesSidebar.setGeometry(QtCore.QRect(0, 240, 100, 80))
        self.btnResourcesSidebar.setStyleSheet("background-color: rgb(40, 57, 83); \n"
"color: white;\n"
"font: 16pt \"Lora\";")
        self.btnResourcesSidebar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/milk-box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResourcesSidebar.setIcon(icon4)
        self.btnResourcesSidebar.setIconSize(QtCore.QSize(60, 60))
        self.btnResourcesSidebar.setObjectName("btnResourcesSidebar")
        self.btnRefillSidebar = QtWidgets.QPushButton(self.sidebar)
        self.btnRefillSidebar.setGeometry(QtCore.QRect(0, 320, 100, 80))
        self.btnRefillSidebar.setStyleSheet("background-color: rgb(40, 57, 83); \n"
"color: white;\n"
"font: 16pt \"Lora\";")
        self.btnRefillSidebar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/coffee-filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefillSidebar.setIcon(icon5)
        self.btnRefillSidebar.setIconSize(QtCore.QSize(60, 60))
        self.btnRefillSidebar.setObjectName("btnRefillSidebar")
        self.horizontalLayout.addWidget(self.sidebar)
        self.stack = QtWidgets.QWidget(self.centralwidget)
        self.stack.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(89, 122, 170, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.stack.setObjectName("stack")
        self.stackedPages = QtWidgets.QStackedWidget(self.stack)
        self.stackedPages.setEnabled(True)
        self.stackedPages.setGeometry(QtCore.QRect(0, 0, 701, 481))
        self.stackedPages.setStyleSheet("")
        self.stackedPages.setObjectName("stackedPages")
        self.blankPage = QtWidgets.QWidget()
        self.blankPage.setObjectName("blankPage")
        self.stackedPages.addWidget(self.blankPage)
        self.horizontalLayout.addWidget(self.stack)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/log-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLogin.setIcon(icon6)
        self.actionLogin.setObjectName("actionLogin")
        self.actionSign_up = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/sign-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSign_up.setIcon(icon7)
        self.actionSign_up.setObjectName("actionSign_up")
        self.actionStats = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/analytics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStats.setIcon(icon8)
        self.actionStats.setObjectName("actionStats")
        self.actionResources = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/milk-box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResources.setIcon(icon9)
        self.actionResources.setObjectName("actionResources")
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProfile.setIcon(icon10)
        font = QtGui.QFont()
        self.actionProfile.setFont(font)
        self.actionProfile.setObjectName("actionProfile")
        self.actionRefill = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/coffee-filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefill.setIcon(icon11)
        self.actionRefill.setObjectName("actionRefill")
        self.actionRating = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/rating.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRating.setIcon(icon12)
        self.actionRating.setObjectName("actionRating")

        self.retranslateUi(MainWindow)
        self.stackedPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionSign_up.setText(_translate("MainWindow", "Sign up"))
        self.actionStats.setText(_translate("MainWindow", "Stats"))
        self.actionResources.setText(_translate("MainWindow", "Resources"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
        self.actionRefill.setText(_translate("MainWindow", "Refill"))
        self.actionRating.setText(_translate("MainWindow", "Rating"))
